"""add_institution_type_to_college

Revision ID: 808c5f7ac5dc
Revises: 2d602f1493f7
Create Date: 2026-09-16 20:40:46.152581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808c5f7ac5dc'
down_revision = '2d602f1493f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.drop_column('institution_type')

    # ### end Alembic commands ###
